version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Employees
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 8080:80
  
  flask:
    build: ./flask
    container_name: flask
    volumes:
      - ./flask:/flask
    depends_on:
      - db
    expose:
      - 9000


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:8000"

